spring:
  application:
    name: wallet
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

auth:
  security:
    base64-auth-secret: test+base64
    expire-time: 3600
    log-validation-exceptions: true

jwt:
  algorithm: HS256
  issuer: ing-wallet
  expiration: 180s
  secret-key: RNJlNM4SUAnfN7BZD2pDtVVMHBjkw0cJySLt5MQ7O5jpkSc9

crypto:
  secret-key: BNKG5J3YPX2L6YlpEmcwTor629D1zzcE
  secret-key-algorithm: AES
  transformation: AES/GCM/NoPadding
  gcm-tag-length: 16
  gcm-iv-length: 12

logging:
  level:
    root: INFO
    com.ing.wallet: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui